name: Django CI with PostgreSQL & Conda

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_DB: expense_tracker_db
          POSTGRES_USER: rudra
          POSTGRES_PASSWORD: Vgtr123!
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U rudra"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Add conda to system path
      run: echo $CONDA/bin >> $GITHUB_PATH

    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name base
        conda activate base
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Apply Database Migrations
      env:
        DATABASE_NAME: expense_tracker_db
        DATABASE_USER: rudra
        DATABASE_PASSWORD: Vgtr123!
        DATABASE_HOST: localhost
        DATABASE_PORT: 5432
      run: |
        python manage.py makemigrations
        python manage.py migrate

    - name: Run Tests with pytest
      run: |
        conda install -y pytest
        pytest --maxfail=5 --disable-warnings --cov=.

    - name: Upload Coverage Report
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        fail_ci_if_error: true
